export const LENGTH_CHANGE = 'LENGTH_CHANGE';
export const TICK = 'TICK';
export const START_POMODORO = 'START_POMODORO';
export const STOP_POMODORO = 'STOP_POMODORO';
export const STORE_SCHEDULED_NOTIFICATION = 'STORE_SCHEDULED_NOTIFICATION';
export const CANCEL_CURRENT_NOTIFICATION = 'CANCEL_CURRENT_NOTIFICATION';
